model_list:
  - model_name: default
    litellm_params:
      model: gemini/gemini-2.5-flash-lite
      api_key: os.environ/GEMINI_API_KEY
  
  - model_name: embedding
    litellm_params:
      model: gemini/text-embedding-004
      api_key: os.environ/GEMINI_API_KEY

router_settings:
  num_retries: 8
  retry_after_rate_limit_error: 10
  routing_strategy: simple-shuffle

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  
litellm_settings:
  drop_params: true
  set_verbose: false
