spring:
  application:
    name: upflow-feedback

  flyway:
    baseline-on-migrate: on

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  error:
    base-uri: ${APP_ERROR_BASE_URI}